"""The account holder's names and identifier: where an export states them, and that
the tables no longer show them.

Synthetic archives only (ADR-0014). The account here is Jane Example, formerly Jane
Sample, username jane.example.
"""
import io
import json
import zipfile
from collections import Counter

import pandas as pd
import pytest

import port.helpers.validate as validate
import port.platforms.facebook as facebook
from port.helpers.extraction_helpers import ZipArchiveReader


def _reader(*entries: tuple[str, str]) -> ZipArchiveReader:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, content in entries:
            zf.writestr(name, content)
    buf.seek(0)
    return ZipArchiveReader(buf, [name for name, _ in entries], Counter())


def _profile_json(uri: str | None = "https://www.facebook.com/jane.example", **extra) -> str:
    profile = {
        "name": {"full_name": "Jane Example", "first_name": "Jane", "middle_name": "", "last_name": "Example"},
        "other_names": [{"name": "Jane Sample", "type": "MAIDEN", "timestamp": 1500000000}],
        "previous_names": [],
    }
    if uri is not None:
        profile["profile_uri"] = uri
    profile.update(extra)
    return json.dumps({"profile_v2": profile})


def _page(body: str = "", name: str = "Jane Example") -> str:
    return (
        '<html><head><meta charset="utf-8"></head><body><header>'
        f'<aside role="contentinfo" class="_aoaa">Generated by {name} on '
        '<time datetime="2026-09-02T13:11Z">Sep 02, 2026</time></aside></header>'
        f"<main>{body}</main></body></html>"
    )


def _profile_page(link: str = "https://www.facebook.com/jane.example", name: str = "Jane Example") -> str:
    return _page(
        "<table>"
        f"<tr><th>Name</th><td>{name}<br /></td></tr>"
        f'<tr><th>Profile</th><td><a href="{link}">{link}</a></td></tr>'
        "<tr><th>Other names</th><td><ul><li>Jane Sample</li></ul></td></tr>"
        "</table>",
        name=name,
    )


def _reactions(*actors: str) -> str:
    return json.dumps([
        {"timestamp": 1750000000 + n, "title": f"{actor} liked a post.",
         "data": [{"reaction": {"reaction": "LIKE", "actor": actor}}]}
        for n, actor in enumerate(actors)
    ])


PROFILE_JSON = "personal_information/profile_information/profile_information.json"
PROFILE_HTML = "personal_information/profile_information/profile_information.html"
REACTIONS = "your_facebook_activity/comments_and_reactions/likes_and_reactions_1.json"
ACCOUNT_ID = "100012345678901"
NOBODY = facebook.AccountHolder()


class TestAccountHolderFromJson:
    def test_names_and_username_come_from_the_profile_file(self):
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json())))
        assert holder == facebook.AccountHolder(("Jane Example", "Jane Sample"), "jane.example")

    def test_an_account_without_a_username_gives_its_id(self):
        uri = f"https://www.facebook.com/profile.php?id={ACCOUNT_ID}"
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier == ACCOUNT_ID

    def test_a_link_that_ends_in_a_number_gives_the_id(self):
        uri = f"https://www.facebook.com/{ACCOUNT_ID}"
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier == ACCOUNT_ID

    def test_a_link_to_somewhere_else_gives_nothing(self):
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json("https://example.org/jane"))))
        assert holder.identifier is None

    def test_a_previous_name_written_as_a_record_or_as_text_is_taken(self):
        extra = {"previous_names": [{"name": "Jane Earlier", "timestamp": 1}, "Jane Before"]}
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(**extra))))
        assert set(holder.names) == {"Jane Example", "Jane Sample", "Jane Earlier", "Jane Before"}

    def test_a_longer_name_stands_before_the_name_it_contains(self):
        extra = {"other_names": [{"name": "Jane Example-Sample", "type": "OTHER", "timestamp": 1}]}
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(**extra))))
        assert holder.names == ("Jane Example-Sample", "Jane Example")

    def test_a_name_stored_as_escaped_bytes_is_decoded(self):
        profile = _profile_json().replace("Jane Example", "Jan\\u00c3\\u00a9 Example")
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, profile)))
        assert "Jané Example" in holder.names

    def test_a_profile_file_of_another_shape_resolves_nothing(self):
        assert facebook._resolve_account_holder(_reader((PROFILE_JSON, json.dumps(["unexpected"])))) == NOBODY

    def test_a_field_the_profile_file_lacks_is_asked_of_the_next_source(self):
        """The names from the profile file, the identifier from the package name."""
        reader = _reader((PROFILE_JSON, _profile_json(uri=None)))
        holder = facebook._resolve_account_holder(reader, "facebook-janeexample-2026-09-02-6zxl8WMW.zip")
        assert holder == facebook.AccountHolder(("Jane Example", "Jane Sample"), "janeexample")

    def test_a_host_that_only_ends_like_facebook_gives_nothing(self):
        uri = "https://notfacebook.com/jane.example"
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier is None

    @pytest.mark.parametrize("uri", [
        "https://www.facebook.com/2026",
        "https://www.facebook.com/profile.php?id=2026",
        "https://www.facebook.com/jane",
        "https://www.facebook.com/j.a",
    ])
    def test_an_identifier_shorter_than_five_characters_is_not_taken(self, uri):
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier is None

    def test_an_identifier_of_five_characters_is_taken(self):
        uri = "https://www.facebook.com/janee"
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier == "janee"

    @pytest.mark.parametrize("uri", [
        "facebook.com/jane.example", "www.facebook.com/jane.example/", "//facebook.com/jane.example",
    ])
    def test_a_link_without_a_scheme_is_read_as_one_with(self, uri):
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier == "jane.example"

    def test_a_profile_link_with_a_value_that_is_not_an_id_leaves_it_to_the_package_name(self):
        """A broken export writes ``profile.php?id=undefined``. That is no id, and it must
        not stand in the way of the next source."""
        reader = _reader((PROFILE_JSON, _profile_json("https://www.facebook.com/profile.php?id=undefined")))
        holder = facebook._resolve_account_holder(reader, "facebook-janeexample-2026-09-02-6zxl8WMW.zip")
        assert holder.identifier == "janeexample"

    def test_a_subdomain_of_facebook_is_accepted(self):
        uri = "https://m.facebook.com/jane.example/"
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(uri))))
        assert holder.identifier == "jane.example"

    def test_a_blank_name_in_the_profile_file_leaves_the_name_open_for_the_next_source(self):
        profile = json.dumps({"profile_v2": {"name": {"full_name": " "}, "other_names": []}})
        reader = _reader((PROFILE_JSON, profile), (REACTIONS, _reactions("Jane Example", "Jane Example")))
        assert facebook._resolve_account_holder(reader).names == ("Jane Example",)

    def test_an_entry_of_another_shape_among_the_other_names_does_not_lose_the_rest(self):
        extra = {"other_names": [42, {"name": "Jane Sample", "type": "MAIDEN", "timestamp": 1}, {"type": "x"}]}
        holder = facebook._resolve_account_holder(_reader((PROFILE_JSON, _profile_json(**extra))))
        assert holder.names == ("Jane Example", "Jane Sample")


class TestResolvingCountsNothing:
    def test_a_profile_file_that_cannot_be_parsed_counts_nothing(self):
        reader = _reader((PROFILE_JSON, "{not json"))
        assert facebook._resolve_account_holder(reader) == NOBODY
        assert reader.errors == Counter()

    def test_two_profile_files_count_nothing(self):
        reader = _reader(("a/" + PROFILE_JSON, _profile_json()), ("b/" + PROFILE_JSON, _profile_json()))
        facebook._resolve_account_holder(reader)
        assert reader.errors == Counter()


class TestAccountHolderFromHtml:
    def test_the_profile_page_gives_names_and_username(self):
        holder = facebook._resolve_account_holder(_reader((PROFILE_HTML, _profile_page())))
        assert holder == facebook.AccountHolder(("Jane Example", "Jane Sample"), "jane.example")

    def test_without_the_profile_page_the_name_comes_from_the_header_of_the_start_page(self):
        holder = facebook._resolve_account_holder(_reader(("start_here.html", _page())))
        assert holder == facebook.AccountHolder(("Jane Example",), None)

    def test_an_account_without_a_username_gives_its_id(self):
        link = f"https://www.facebook.com/profile.php?id={ACCOUNT_ID}"
        holder = facebook._resolve_account_holder(_reader((PROFILE_HTML, _profile_page(link))))
        assert holder.identifier == ACCOUNT_ID

    def test_an_apostrophe_written_as_an_entity_is_decoded(self):
        holder = facebook._resolve_account_holder(_reader((PROFILE_HTML, _profile_page(name="Jane O&#039;Example"))))
        assert "Jane O'Example" in holder.names

    def test_a_name_inside_a_link_in_the_header_is_read_without_its_markup(self):
        page = _page().replace("Jane Example", '<a href="#">Jane Example</a>')
        holder = facebook._resolve_account_holder(_reader(("start_here.html", page)))
        assert holder.names == ("Jane Example",)

    def test_a_name_that_contains_the_word_on_is_read_whole(self):
        holder = facebook._resolve_account_holder(_reader(("start_here.html", _page(name="Jane on Example"))))
        assert holder.names == ("Jane on Example",)

    def test_the_header_is_read_whatever_follows_the_stamp(self):
        page = _page().replace("</time></aside>", "</time>\n  </aside>")
        assert facebook._resolve_account_holder(_reader(("start_here.html", page))).names == ("Jane Example",)

    def test_a_profile_page_without_a_usable_name_leaves_it_to_the_start_page(self):
        profile = (
            '<html><head><meta charset="utf-8"></head><body><main><table>'
            "<tr><th>Name</th><td> <br /></td></tr>"
            '<tr><th>Profile</th><td><a href="https://www.facebook.com/jane.example">x</a></td></tr>'
            "</table></main></body></html>"
        )
        reader = _reader((PROFILE_HTML, profile), ("start_here.html", _page()))
        assert facebook._resolve_account_holder(reader) == facebook.AccountHolder(("Jane Example",), "jane.example")

    def test_a_page_without_the_header_resolves_nothing(self):
        assert facebook._resolve_account_holder(_reader(("start_here.html", "<html><body/></html>"))) == NOBODY


class TestNameFromTheReactionsFile:
    def test_every_reaction_by_the_same_actor_gives_the_name(self):
        reader = _reader((REACTIONS, _reactions("Jane Example", "Jane Example", "Jane Example")))
        assert facebook._resolve_account_holder(reader).names == ("Jane Example",)

    def test_two_actors_give_nothing(self):
        """The file holds the participant's own reactions. If it names more than one
        actor it is not the file this rule understands, and the more frequent of the
        two could be another person."""
        reader = _reader((REACTIONS, _reactions("Jane Example", "Jane Example", "John Example")))
        assert facebook._resolve_account_holder(reader).names == ()

    def test_the_profile_file_is_preferred_and_the_reactions_file_not_opened(self, monkeypatch):
        reader = _reader((PROFILE_JSON, _profile_json()), (REACTIONS, _reactions("Someone Else")))
        opened = []
        json_all = ZipArchiveReader.json_all
        monkeypatch.setattr(
            ZipArchiveReader, "json_all", lambda self, pattern: opened.append(pattern) or json_all(self, pattern)
        )
        assert "Someone Else" not in facebook._resolve_account_holder(reader).names
        assert opened == []

    def test_no_reactions_give_nothing(self):
        assert facebook._resolve_account_holder(_reader((REACTIONS, "[]"))).names == ()


class TestIdentifierFromThePackageName:
    @pytest.mark.parametrize("package_name", [
        "facebook-janeexample-2026-09-02-6zxl8WMW.zip",
        "facebook_janeexample_2026_03_02_IE4jDkhF_20260309T102720Z.zip",
        "facebook-janeexample-12_06_2026-n88Wfusc.zip",
        "facebook-janeexample-2026-09-02-6zxl8WMW (1).zip",
        "facebook-janeexample-2026-09-02-6zxl8WMW-1.zip",
    ])
    def test_the_name_of_the_zip_gives_the_username(self, package_name):
        reader = _reader(("ads_information/ad_preferences.json", "{}"))
        assert facebook._resolve_account_holder(reader, package_name).identifier == "janeexample"

    def test_a_number_in_its_place_is_the_account_id(self):
        reader = _reader(("ads_information/ad_preferences.json", "{}"))
        holder = facebook._resolve_account_holder(reader, f"facebook-{ACCOUNT_ID}-12_06_2026-n88Wfusc.zip")
        assert holder.identifier == ACCOUNT_ID

    def test_a_folder_inside_the_zip_gives_it_when_the_zip_was_renamed(self):
        member = (
            "meta-2026-Mar-10-16-13-08/facebook-janeexample-2026-03-10-O3oyQ5r2/ads_information/ad_preferences.json"
        )
        holder = facebook._resolve_account_holder(_reader((member, "{}")), "download (3).zip")
        assert holder.identifier == "janeexample"

    def test_two_folders_that_disagree_give_nothing(self):
        reader = _reader(
            ("meta-1/facebook-janeexample-2026-03-10-O3oyQ5r2/a.json", "{}"),
            ("meta-1/facebook-johnexample-2026-03-10-Xy12Zw34/a.json", "{}"),
        )
        assert facebook._resolve_account_holder(reader).identifier is None

    def test_the_profile_link_wins_over_the_package_name(self):
        """The link has the username with its dots; the package name has lost them."""
        reader = _reader((PROFILE_JSON, _profile_json()))
        holder = facebook._resolve_account_holder(reader, "facebook-janeexample-2026-09-02-6zxl8WMW.zip")
        assert holder.identifier == "jane.example"

    @pytest.mark.parametrize("package_name", [
        "my facebook data.zip", "facebook-.-2026-09-02-6zxl8WMW.zip", "facebook-jane-2026-09-02-6zxl8WMW.zip",
        "facebook-2026-2026-09-02-6zxl8WMW.zip", "facebook-janeexample-2026-09-02.zip", "",
    ])
    def test_a_name_of_another_shape_gives_nothing(self, package_name):
        reader = _reader(("ads_information/ad_preferences.json", "{}"))
        assert facebook._resolve_account_holder(reader, package_name) == NOBODY


def _redacted(holder: facebook.AccountHolder, **columns: list) -> pd.DataFrame:
    frame = pd.DataFrame(columns)
    facebook._redact_account_holder([frame], holder)
    return frame


JANE = facebook.AccountHolder(("Jane Example-Sample", "Jane Example", "Jane Sample"), "jane.example")


class TestRedactionOfTextColumns:
    def test_names_and_username_become_the_token(self):
        frame = _redacted(JANE, Title=["Jane Example liked a post", "jane sample's photo", "by janeexample"])
        assert list(frame["Title"]) == ["[user] liked a post", "[user]'s photo", "by [user]"]

    def test_a_name_is_matched_across_any_whitespace(self):
        frame = _redacted(JANE, Title=["Jane  Example wrote", "Jane Example wrote", "Jane\tExample"])
        assert list(frame["Title"]) == ["[user] wrote", "[user] wrote", "[user]"]

    def test_a_name_that_contains_another_is_redacted_whole(self):
        assert list(_redacted(JANE, Title=["Jane Example-Sample wrote"])["Title"]) == ["[user] wrote"]

    def test_another_person_whose_name_begins_with_it_is_left(self):
        frame = _redacted(JANE, Title=["Jane Example-Smith wrote", "Jane Examples", "John Example"])
        assert list(frame["Title"]) == ["Jane Example-Smith wrote", "Jane Examples", "John Example"]

    def test_an_address_becomes_its_own_token_also_when_it_holds_the_username(self):
        frame = _redacted(JANE, Comment=["write to jane.example@example.org or a@b.nl"])
        assert list(frame["Comment"]) == ["write to [email] or [email]"]

    def test_the_username_inside_a_longer_word_is_left(self):
        frame = _redacted(JANE, Comment=["jane.examples", "xjane.example", "janeexample2"])
        assert list(frame["Comment"]) == ["jane.examples", "xjane.example", "janeexample2"]

    def test_a_domain_named_after_the_account_holder_is_redacted(self):
        """Such a domain names them as surely as the username does."""
        frame = _redacted(JANE, Comment=["see www.janeexample.nl", "jane.example.com/about"])
        assert list(frame["Comment"]) == ["see www.[user].nl", "[user].com/about"]

    def test_a_username_known_with_its_dots_does_not_match_other_dots(self):
        assert list(_redacted(JANE, Comment=["j.ane.example"])["Comment"]) == ["j.ane.example"]

    def test_a_username_known_without_dots_matches_the_dotted_spelling(self):
        holder = facebook.AccountHolder((), "janeexample")
        assert list(_redacted(holder, Comment=["facebook.com/jane.example"])["Comment"]) == ["facebook.com/[user]"]

    def test_the_search_terms_are_a_text_column(self):
        frame = _redacted(JANE, **{"Search term": ["Jane Example", "bicycles"]})
        assert list(frame["Search term"]) == ["[user]", "bicycles"]

    def test_missing_cells_stay_missing(self):
        frame = _redacted(JANE, Title=["Jane Example", None])
        assert frame["Title"][0] == "[user]" and pd.isna(frame["Title"][1])

    def test_nobody_resolved_still_redacts_addresses(self):
        frame = _redacted(NOBODY, Title=["Jane Example wrote to a@b.nl"])
        assert list(frame["Title"]) == ["Jane Example wrote to [email]"]

    def test_a_name_with_characters_special_to_a_pattern_is_taken_literally(self):
        holder = facebook.AccountHolder(("J. (Jane) Example",), None)
        assert list(_redacted(holder, Title=["J. (Jane) Example wrote", "Jx (Jane) Example"])["Title"]) == [
            "[user] wrote", "Jx (Jane) Example",
        ]


class TestRedactionOfLinkColumns:
    def test_the_username_is_redacted_and_the_rest_of_the_link_kept(self):
        frame = _redacted(JANE, URL=["https://www.facebook.com/jane.example/posts/123", "https://example.org/jane"])
        assert list(frame["URL"]) == ["https://www.facebook.com/[user]/posts/123", "https://example.org/jane"]

    def test_the_account_id_is_redacted_as_a_whole_number_only(self):
        holder = facebook.AccountHolder((), ACCOUNT_ID)
        frame = _redacted(holder, URL=[f"https://www.facebook.com/profile.php?id={ACCOUNT_ID}", f"id={ACCOUNT_ID}2"])
        assert list(frame["URL"]) == ["https://www.facebook.com/profile.php?id=[user]", f"id={ACCOUNT_ID}2"]

    def test_a_domain_named_after_the_account_holder_is_redacted_in_a_link(self):
        frame = _redacted(JANE, URL=["https://www.janeexample.nl/photos", "https://janeexamples.nl"])
        assert list(frame["URL"]) == ["https://www.[user].nl/photos", "https://janeexamples.nl"]

    def test_neither_a_name_nor_an_address_is_looked_for_in_a_link(self):
        frame = _redacted(JANE, URL=["https://example.org/Jane Example?mail=a@b.nl"], Link=["mailto:a@b.nl"])
        assert list(frame["URL"]) == ["https://example.org/Jane Example?mail=a@b.nl"]
        assert list(frame["Link"]) == ["mailto:a@b.nl"]

    def test_without_an_identifier_a_link_column_is_not_touched(self):
        frame = pd.DataFrame({"URL": ["https://example.org"]})
        before = frame["URL"].dtype
        facebook._redact_account_holder([frame], facebook.AccountHolder(("Jane Example",), None))
        assert frame["URL"].dtype == before


def _search_page(*terms: str, header: bool = True) -> str:
    sections = "".join(
        f'<section class="_a6-g"><div class="_2pin"><div>"{term}"</div></div>'
        '<footer><div class="_a72d">Jan 01, 2026 9:00:00 am</div></footer></section>'
        for term in terms
    )
    return _page(sections) if header else f"<html><body><main>{sections}</main></body></html>"


class _Upload(io.BytesIO):
    """An upload with a file name, as the adapter in the browser has."""
    name = ""


def _tables(package_name: str, *entries: tuple[str, str]) -> tuple[dict, Counter]:
    buf = _Upload()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, content in entries:
            zf.writestr(name, content)
        zf.writestr("connections/followers/who_you've_followed.html", "<html/>")
        zf.writestr("ads_information/ad_preferences.html", "<html/>")
    buf.seek(0)
    buf.name = package_name
    validation = validate.validate_zip(facebook.DDP_CATEGORIES, buf)
    assert validation.get_status_code_id() == 0
    result = facebook.extraction(buf, validation)
    return {t.id: t.data_frame for t in result.tables}, result.errors


SEARCH_HTML = "logged_information/search/your_search_history.html"


class TestExtractionRedacts:
    def test_an_html_export_without_a_profile_page(self):
        tables, _errors = _tables(
            "facebook-janeexample-2026-09-02-gpgIKVJQ.zip",
            ("start_here.html", _page()),
            (SEARCH_HTML, _search_page("Jane Example", "janeexample", "bicycles")),
        )
        assert sorted(tables["facebook_search_history"]["Search term"]) == ["[user]", "[user]", "bicycles"]

    def test_nothing_resolved_redacts_nothing_and_counts_no_error(self):
        tables, errors = _tables("my facebook data.zip", (SEARCH_HTML, _search_page("Jane Example", header=False)))
        assert list(tables["facebook_search_history"]["Search term"]) == ["Jane Example"]
        # The html clock has no timezone file here and says so; nothing else is counted.
        assert set(errors) <= {"HtmlTimezoneUnknown"}
